BotInfo:
  Token:  #put it inside ""
  OwnerID:
  ServerID:
Settings:
  Status: "DND" #Available statuses: DND, ONLINE, IDLE, INVISIBLE
  Activity: "PLAYING" #Available activities: PLAYING, WATCHING, LISTENING (Leave blank for nothing)
  ActivityName: "Supporting people !"
  TicketsCategory:  #Category under which tickets will be created
  SupportRole:  #ID of your support role
  TicketName: "%name's ticket"  #You can also use %randomID to generate a random ticket id
  StaffChannel:   #Embeds for tickets would be sent here
Tickets:
  MaxTickets: 5 #Maximum number of tickets per user
  MaxExtended: "You have reached the maximum amount of tickets allowed for you, please wait for one to be closed"
  ModalTitle: "Issue report !"
  IssueTitle: "Issue"
  ModalTitlePlaceholder: "What's the issue ?"
  IssueDescription: "Issue description"
  ModalDescriptionPlaceholder: "Describe your issue here !"
  SentIssue: "Successfully sent issue!"
  ButtonText: "☑ Open ticket"
  CloseButtonText: "Close ticket"
  AddToTicketYES: "YES"
  AddToTicketNO: "NO"
  CantAdd: "Sorry, but you cant add this person to channel !"
Keywords:
  test:
    Response:
      - "This is a test response"
      - "This is another test response"
    Emoji: "U+1F600" #this is going to be reacted on the message with keyword